### ISSUE TITLE
Making vcov argument optional in crosspred() ?

### ISSUE THREAD

**Issue by osupplisson** [gasparrini/dlnm#14]
Hello,

First of all, thank you very much for your work and package, which are really useful !

I am trying to implement a DNLM using INLA (through inlabru) (https://www.r-inla.org/ and https://inlabru-org.github.io/inlabru/).

I am currently having a closer look at how I could interpret results I would get from INLA and notably how I could depict the link between the initial marginal bases (exposure history and lag) and the values of the bidimensional smoothing splines.

It seems that the way to go is through the `crosspred()` function, which does not support model from INLA but allows to input estimated coefs and vcov. However, I would rather like to apply this function to several joint posterior draws and then work with the posterior distribution of the values.

It seems that the function cannot work without a vcov input, could you consider make this argument optional for Bayesian analyses or maybe make this function more general so that it can directly work with posterior draws (i.e. deriving cumlow 
 and cumhigh using the draws) ?

I made a small reprex below to illustrate the problem:

```
# Package -----------------------------------------------------------------
#For installing INLA:
#install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)
library(INLA)
library(dlnm)


# Dummy variables ---------------------------------------------------------
x <- rpois(100, 3)
Y <- rnorm(0.5 + 0.6 * x, 0, 1)


# from X to B-spline basis ------------------------------------------------
basis <- onebasis(x, fun = "ps")
A_mat <- basis
attributes(A_mat) <- attributes(A_mat)["dim"]


# Penalty matrix ----------------------------------------------------------
Cmat <- Matrix(dlnm::cbPen(basis)$Svar, sparse = TRUE)


# Fit -----------------------------------------------------------------
fit <- inla(
  Y ~ -1 + f(
    i,
    constr = T,
    Cmatrix = Cmat,
    model = "generic0"
  ),
  data = list(Y = Y, i = 1:ncol(A_mat)),
  control.predictor = list(A = A_mat),
  control.compute=list(config = TRUE),
  verbose = T
)

# Draws -------------------------------------------------------------------
posterior_draw <- inla.posterior.sample(n = 1L, fit)


# Manual computation ------------------------------------------------------
A_mat %*% posterior_draw[[1]]$latent[paste0("i:",1:10),]


# Trying crosspred-------------------------------------------------------------------------
crosspred(basis,
          model=NULL, 
          coef= posterior_draw[[1]]$latent[paste0("i:",1:10),],
          vcov=NULL, 
          model.link=NULL,
          at = 1)
##Erreur dans crosspred(basis, model = NULL, coef = posterior_draw[[1]]$latent[paste0("i:",  : 
# At least 'model' or 'coef'-'vcov' must be provided
```

I hope I don't miss something obvious.

Best,
Olivier

Ps: I could have a closer look at the function and maybe make changes myself, but I feel this might be a bit error-prone so I prefer asking, just in case.

**Comment by gasparrini** [comment]
Thanks for your interest.
You can bypass the problem by including a fictional `vcov`, for instance using:
```
vcov <- diag(0.1, length(posterior_draw[[1]]$latent[paste0("i:",1:10),]))
```
Probably the direct use of `crosspred()` will be quite inefficient as it re-creates internally all the objects needed for the prediction. Anyway, I think it will be safer for the average user compared to performing the prediction manually.

Best
-Antonio Gasparrini

**Comment by osupplisson** [comment]
Thank you very much for your reply.

I had in mind this solution but wasn't sure it would be ok. I'll follow this solution.

Best,
Olivier
