### ISSUE TITLE
Question about the reference group

### ISSUE THREAD

**Issue by yangepi** [gasparrini/dlnm#8]
Thank you for this cool package, I have a question about what is the reference group.

For example, the crossbasis is like this:
dlnm::crossbasis(lagx:lagy, zmaxlag, argvar = list(fun='integer'), arglag = list(fun='ns',knots= best_knot_pos))

My predictor is either 0 or 1 for each t-lag day, However, the participants were all exposed to the risk (coded as 1), just different on t-lag day. So, the data don't have an unexposed group.

I found the dlnm still can give each lag day RR_lag, and the overall RR_all. 

I think each lag day's RR_lag, comes from comparing the predictor of 1 to 0 at that lag day on the final outcome. But how the model control for other days? Are all other days held at an average level and then compare 1 to 0 at that lag day? Because my participants were all exposed to the risk, so I think comparing the predictor of 1 to 0 at one lag day means comparing the predictor of 1 to all those exposed at other days?

I am not sure what is the reference of the overall RR_all between lagx and lagy? Because my data don't have any observation having predictor = 0 through the whole time between lagx and lagy, so how the model dealing with that? Is the average of all the data except the lagx and lagy used instead? If the model show a cumulative effect of a period of "P", it seems that it comparing predict all = 1 to all = 0 during the "P" which in my case maybe comparing predict = 1 during "P" to all exposed during another time period? If that is the case, the whole period's cumulative effect's reference level is which one?

Thank you.

Thank you.

**Comment by gasparrini** [comment]
Dear Yang,

Thanks for your interest.
The DLNM methodology is based on the comparison of predictors levels at different lags, not just between observations.
Therefore, it is not a problem that all subject experience the exposure (coded as a binary 0-1), provided that they do so at different times in the past (lags).

The fitted model can then be used to predict for different exposure histories. The usual (allRR*) reports the case when all the lags are exposed vs none is, which is a predicted risk that can be computed even when none of the subjects has this exposure history. However, you can also define other comparisons, for instance by including a matrix of exposure histories (even a 1-row matrix) in the argument ‘at’.

I hope it is clear.

Best
-Antonio Gasparrini
