### ISSUE TITLE
crossbasis for a factor variable

### ISSUE THREAD

**Issue by Fred-Wu** [gasparrini/dlnm#9]
I am conducting an study which is not only looking at an overall exposure-lag-response, but group level effect as well. 
Is there anyway to specify crossbasis for different groups, like “by” argument in the mgcv package?

**Comment by gasparrini** [comment]
Thanks for the question.
There is no 'by' argument, but you can easily fit such kind of model using standard interaction terms and then manually extracting the parameters for prediction.

For instance, if you have a cross-basis object cb and a factor fac that takes values 'a' and 'b', you can:
- specify an interaction cb:fac in the model formula and therefore obtain sets of parameters cb:faca and  cb:facb
- extract the two sets of coef/vcov from each category [e.g., by using grep('cb:faca', names(coef(model)), fixed=T)], and use the corresponding arguments in crosspred() to obtain predictions

You can find more complex examples of such an approach for specifying linear interactions here:
http://www.ag-myresearch.com/2015_gasparrini_ehp.html
http://www.ag-myresearch.com/2016_gasparrini_aje.html
